#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : cryptsetup
Version  : 2.0.6
Release  : 61
URL      : https://www.kernel.org/pub/linux/utils/cryptsetup/v2.0/cryptsetup-2.0.6.tar.xz
Source0  : https://www.kernel.org/pub/linux/utils/cryptsetup/v2.0/cryptsetup-2.0.6.tar.xz
Summary  : cryptsetup library
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 LGPL-2.1
Requires: cryptsetup-bin = %{version}-%{release}
Requires: cryptsetup-config = %{version}-%{release}
Requires: cryptsetup-lib = %{version}-%{release}
Requires: cryptsetup-license = %{version}-%{release}
Requires: cryptsetup-locales = %{version}-%{release}
Requires: cryptsetup-man = %{version}-%{release}
Requires: cryptsetup-python = %{version}-%{release}
Requires: cryptsetup-python3 = %{version}-%{release}
Requires: LVM2
Requires: LVM2-extras
BuildRequires : keyutils-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(devmapper)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pwquality)
BuildRequires : popt-dev
BuildRequires : python3-dev
Patch1: 0001-pycryptsetup-test.py-change-python-interpreter.patch

%description
cryptsetup
setup cryptographic volumes for dm-crypt (including LUKS extension)
WEB PAGE:

%package bin
Summary: bin components for the cryptsetup package.
Group: Binaries
Requires: cryptsetup-config = %{version}-%{release}
Requires: cryptsetup-license = %{version}-%{release}

%description bin
bin components for the cryptsetup package.


%package config
Summary: config components for the cryptsetup package.
Group: Default

%description config
config components for the cryptsetup package.


%package dev
Summary: dev components for the cryptsetup package.
Group: Development
Requires: cryptsetup-lib = %{version}-%{release}
Requires: cryptsetup-bin = %{version}-%{release}
Provides: cryptsetup-devel = %{version}-%{release}
Requires: cryptsetup = %{version}-%{release}

%description dev
dev components for the cryptsetup package.


%package lib
Summary: lib components for the cryptsetup package.
Group: Libraries
Requires: cryptsetup-license = %{version}-%{release}

%description lib
lib components for the cryptsetup package.


%package license
Summary: license components for the cryptsetup package.
Group: Default

%description license
license components for the cryptsetup package.


%package locales
Summary: locales components for the cryptsetup package.
Group: Default

%description locales
locales components for the cryptsetup package.


%package man
Summary: man components for the cryptsetup package.
Group: Default

%description man
man components for the cryptsetup package.


%package python
Summary: python components for the cryptsetup package.
Group: Default
Requires: cryptsetup-python3 = %{version}-%{release}

%description python
python components for the cryptsetup package.


%package python3
Summary: python3 components for the cryptsetup package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cryptsetup package.


%package staticdev
Summary: staticdev components for the cryptsetup package.
Group: Default
Requires: cryptsetup-dev = %{version}-%{release}

%description staticdev
staticdev components for the cryptsetup package.


%prep
%setup -q -n cryptsetup-2.0.6
%patch1 -p1
pushd ..
cp -a cryptsetup-2.0.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556042832
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure  --with-crypto_backend=gcrypt --enable-python --with-python_version=3 --enable-static --enable-pwquality
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%configure  --with-crypto_backend=gcrypt --enable-python --with-python_version=3 --enable-static --enable-pwquality
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../buildavx2;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1556042832
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cryptsetup
cp COPYING %{buildroot}/usr/share/package-licenses/cryptsetup/COPYING
cp COPYING.LGPL %{buildroot}/usr/share/package-licenses/cryptsetup/COPYING.LGPL
cp lib/crypto_backend/argon2/LICENSE %{buildroot}/usr/share/package-licenses/cryptsetup/lib_crypto_backend_argon2_LICENSE
pushd ../buildavx2/
%make_install_avx2
popd
%make_install
%find_lang cryptsetup

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cryptsetup
/usr/bin/cryptsetup-reencrypt
/usr/bin/haswell/cryptsetup
/usr/bin/haswell/cryptsetup-reencrypt
/usr/bin/haswell/integritysetup
/usr/bin/haswell/veritysetup
/usr/bin/integritysetup
/usr/bin/veritysetup

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/cryptsetup.conf

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/haswell/libcryptsetup.so
/usr/lib64/libcryptsetup.so
/usr/lib64/pkgconfig/libcryptsetup.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libcryptsetup.so.12
/usr/lib64/haswell/libcryptsetup.so.12.3.0
/usr/lib64/libcryptsetup.so.12
/usr/lib64/libcryptsetup.so.12.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cryptsetup/COPYING
/usr/share/package-licenses/cryptsetup/COPYING.LGPL
/usr/share/package-licenses/cryptsetup/lib_crypto_backend_argon2_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/cryptsetup-reencrypt.8
/usr/share/man/man8/cryptsetup.8
/usr/share/man/man8/integritysetup.8
/usr/share/man/man8/veritysetup.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libcryptsetup.a

%files locales -f cryptsetup.lang
%defattr(-,root,root,-)

